### ISSUE TITLE
Library fails with Arduino Core for ESP8266 v2.5.1 and above

### ISSUE THREAD

**Issue by xoseperez** [AllWize/allwize#12]
Building and flashing the `master_allwize_k1_esp8266` example with Arduino Core for ESP8266 2.5.1 and above (espressif8266@2.1.1 and above in PlatformIO) 

The Arduino IDE serial monitor shows a "Error connecting to the module, check your wiring!" error. Connecting using miniterm (PlatformIO monitor) show a connection broken sometimes:

```
[MAIN] Wize Master Example
[MAIN] Core version: 2_5_1

Exception in thread rx:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/serial/tools/miniterm.py", line 403, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 495, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

For the moment it is recommended to stick to 2.5.0 or below.

**Comment by SteffCGN** [comment]
I tried this with all Core versions from 2.4.2 to 2.5.2 and always get told to check my wiring.

Any ideas?

Cheers,

Stefan

**Comment by xoseperez** [comment]
I guess you are using the K1, can you check if the jumpers match the position in the image here: http://wiki.allwize.io/index.php?title=Allwize_G1

**Comment by SteffCGN** [comment]
The K1 had a different jumper setting (actually bridges on the board, not jumpers). Just the other way around as in the linked photo. I changed it, but still I get: 
[WIZE] Error connecting to the module, check your wiring!

**Comment by hyvinec** [comment]
I am experiencing the same issue with allWize K1+wemos D1.
jumpers are correctly configured and I get:
[WIZE] Error connecting to the module, check your wiring!

I tried wiring a huzzah feather board instead of wemos D1. I get an answer from the module by deconnecting/connecting power wire but no answer when using reset button.

**Comment by yoyo91120** [comment]
Hello i have the same problem. I try to connect two Modem RC1701HP.
One on Arduino uno and one on ESP8266 (Wemos D1 mini). But on the Wemos D1 mini the example don't work. I have same error. Do you have an photo to connect a Wemos D1 mini. I am in confinment and i don't all my matérial of labs


![IMG_20200324_125546](https://user-images.githubusercontent.com/62600161/77428169-fd1aa700-6dd7-11ea-800f-ef0459d7e164.jpg)
